name: Update the decisions README with a list of decisions

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  merge-md:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Run update script
        run: |
          DECISIONS=""

          for file in decision-record/*.md; do
            if [[ "${file}" != "decision-record/README.md" ]]; then
              FILENAME=$(echo ${file} | cut -f 2 -d '/')
              TITLE=$(cat ${file} | grep -E '^# .+' | cut -f 2- -d " ")
              STATUS=$(cat ${file} | grep -E '\*\*Status:\*\* .+' | cut -f 2- -d " ")
              if [[ "${STATUS}" == "Approved" ]]; then
                DECISIONS="${DECISIONS}\n - [${TITLE}](./${FILENAME}) [${STATUS}]"
              fi
            fi
          done

          echo "Approved decisions found:"
          echo ${DECISIONS}

          SEDFLAGS=':a;N;$!ba;'
          sed -i -E "${SEDFLAGS}s|(<\!-- DO NOT EDIT - AUTOGENERATED -->).*(<\!-- END OF AUTOGENERATED -->)|\1${DECISIONS}\n\2|g"  decision-record/README.md

      - name: Commit and push changes
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy-key
          chmod 600 ~/.ssh/deploy-key
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add ~/.ssh/deploy-key

          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions"
          git add decision-record/README.md
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Auto: Updated README.md with all approved decisions [skip ci]"
          git push
